
version: '3.4'

services:
  rafbot:
    image: rafbot
    restart: always
    build:
      context: .
      dockerfile: RafBot/Dockerfile
    volumes:
      - "./data:/app/data"
    environment:
      - "BOT_TOKEN=${BOT_TOKEN:?}"